[build]
    publish = "dist"
    command = "echo 'Using pre-built files'"

[build.environment]
    NODE_VERSION = "22"
    NPM_FLAGS = "--production=false"

[[redirects]]
   from = "/*"
   to = "/index.html"
   status = 200